create table transaction
(id bigint generated by default as identity,
 wallet_id bigint,
 amount integer not null,
 transaction_type varchar(255),
 remarks VARCHAR(255),
 created_at TIMESTAMP not null,
 primary key (id));
